mysite/argue/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path("", views.overview, name="overview"),
        # path("", views.index, name="index"),
        path("add", views.add, name="add"),
        path("delete/<int:id>", views.delete, name="delete"),
        ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from accounts import views

urlpatterns = [
    path('', views.home, name="home"),
    path('auth/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('argue/', include(('argue.urls', 'argue'), namespace='argue')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
]

mysite/templates/_partial.html
{% block content %}
{% endblock %}

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>{% block title %}Auth Tut{% endblock %}</title>
    <script src="https://unpkg.com/htmx.org@1.9.4" integrity="sha384-zUfuhFKKZCbHTY6aRR46gxiqszMk5tcHjsVFxnUo8VMus4kHGVdIYVbOYYNlKmHV" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@picocss/pico@1/css/pico.min.css">
    <!-- <script src="https://cdn.tailwindcss.com"></script> -->
    <link rel="icon" href="#" />
</head>
<body>
    {% include "accounts/auth_bar.html" %}
    {% include "navbar.html" %}
    <main>
        {% block content %}{% endblock %}
    </main>
</body>
</html>

mysite/templates/home.html
{% extends base_template %}
{% block content %}
{% if user.is_authenticated %}
hi, {{ user.username }}!! You are logged in!
{% else %}
<p>You are not logged in</p>
{% endif %}
{% endblock %}

mysite/templates/navbar.html
    <span><a href={% url 'home' %} hx-target="main" hx-select="main" hx-boost="true">Home</a></span>
    <span><a href={% url 'argue:overview' %} hx-target="main" hx-select="main" hx-boost="true">Overview</a></span>