mysite/accounts/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path('signup/', views.signup, name='signup'),
        path('login/', views.auth_login_form, name='login'),
        path('login_action/', views.auth_login, name='login_action'),
        path('logout/', views.auth_logout, name='logout'),
        path('auth_bar', views.auth_bar, name='auth_bar'),
        path('debug', views.debug, name='debug'),
        ]

mysite/argue/urls.py
from django.urls import path

from . import views

urlpatterns = [
        path("", views.overview, name="overview"),
        # path("", views.index, name="index"),
        path("add", views.add, name="add"),
        path("delete/<int:id>", views.delete, name="delete"),
        ]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView
from accounts import views

urlpatterns = [
    path('', views.home, name="home"),
    path('auth/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('argue/', include(('argue.urls', 'argue'), namespace='argue')),
    path('admin/', admin.site.urls),
    # path('accounts/', include('django.contrib.auth.urls')),
]

mysite/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class CustomUser(AbstractUser):
    pass

    def __str__(self):
        return self.username

mysite/accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ("username", "email")

mysite/accounts/views.py
from .forms import CustomUserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth import authenticate, login, logout
from django.views.decorators.http import require_GET, require_POST


# Create your views here.

@require_GET
def home(request):
    base_template = "base.html"
    response = render(request, 'home.html', {'base_template': base_template})
    response['HX-Trigger'] = 'authAction'
    return response

@require_POST
def auth_login(request):

    # authenticate user
    data = request.POST
    form = AuthenticationForm(data=data)

    if form.is_valid():
        username = data['username']
        password = data['password']
        user = authenticate(
                request,
                username=username,
                password=password
                )
        if user is not None:
            login(request, user)
            print("login")
            base_template = "base.html"
            response = render(request, 'home.html', {'base_template': base_template})
            response['HX-Trigger'] = 'authAction'
            response['HX-Redirect'] = '/'
            return response
        else:
            return redirect('login')

@require_GET
def auth_login_form(request):
    print("auth_login_form_view")
    base_template = "base.html"

    if request.user.is_authenticated:
        print("user is authenticated and returning home page")
        response = render(request, 'home.html', {'base_template': base_template})
        return response

    else:
        print("user is not authenticated and returning login form")
        form = AuthenticationForm()
        response = render(request, 'accounts/login.html', {'form': form,
                                                           'base_template': base_template})
        return response

        
def auth_logout(request):
    print("auth_logout_view")

    print(f"csrf: {request.COOKIES['csrftoken']}")

    if request.htmx:
        base_template = "_partial.html"
    else:
        base_template = "base.html"

    if request.method == 'POST':
        # logout user
        logout(request)
        print("logout")
        print(f"base_template: {base_template}")
        response = render(request, 'home.html', {'base_template': base_template})
        response['HX-Trigger'] = 'authAction'
        response['HX-Redirect'] = '/'
        return response

def signup(request):
    print("signup_view")
    if request.htmx:
        base_template = "_partial.html"
    else:
        base_template = "base.html"
    # return signup form
    if request.method == 'GET':
        return render(request, 'accounts/signup.html', { 'form': CustomUserCreationForm,
                                                         'base_template': base_template})
    elif request.method == 'POST':
        # create new user
        print(f"POST: {request.body}")
        data = request.POST
        form = CustomUserCreationForm(data=data)
        if form.is_valid():
            form.save()

            return HttpResponse("You are signed up!")

def auth_bar(request):
    if request.htmx:
        print("auth_bar_view")
        # just refresh bar
        response = render(request, 'accounts/auth_bar.html')
        return response
    else:
        base_template = "base.html"
        response = render(request, 'home.html', {'base_template': base_template})
        return response

def debug(request):
    print("debug_view")
    return HttpResponse("debug")

mysite/accounts/templates/accounts/auth_bar.html
<div hx-get={% url 'accounts:auth_bar' %}
    hx-trigger="htmx:historyRestore, authAction from:body"
    hx-swap="outerHTML">
{% if user.is_authenticated %}
    <a hx-post={% url 'accounts:logout' %}
        hx-trigger="click"
        hx-target="main"
        hx-swap="innerHTML"
        hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'
        hx-confirm="Are you sure you want to logout?">
        Logout
    </a>
{% else %}
    <a href={% url 'accounts:login' %}
        hx-target="main"
        hx-swap="innerHTML"
        hx-select="main"
        hx-boost="true">
        Login
    </a>
    <a href={% url 'accounts:signup' %}
        hx-target="main"
        hx-swap="innerHTML"
        hx-boost="true">
        Signup
    </a>
{% endif %}
</div>

mysite/accounts/templates/accounts/login.html
{% extends base_template %}
{% block content %}
<h2>Log In</h2>
<form hx-post={% url 'accounts:login_action' %}
    hx-target="main"
    hx-select="main"
    hx-swap="innerHTML"
    hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
    {{ form.as_p }}
    <button type="submit">Log In</button>
</form>
{% endblock %}

mysite/accounts/templates/accounts/signup.html
{% extends base_template %}
{% block content %}
<h2>Sign Up</h2>
<form hx-post={% url 'accounts:signup' %} hx-target="this" hx-swap="outerHTML" hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  {{ form.as_p }}
  <button type="submit">Sign Up</button>
</form>
{% endblock %}